[package]
name = "linux-quest-capture"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
linux-quest-protocol = { path = "../protocol" }
bytes.workspace = true
thiserror.workspace = true
async-trait.workspace = true
tracing.workspace = true
libloading.workspace = true

[dev-dependencies]
tokio.workspace = true
