[package]
name = "linux-quest-protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytes.workspace = true
serde.workspace = true
bincode.workspace = true
crc32fast.workspace = true
thiserror.workspace = true

[dev-dependencies]
